#ifndef EXPRESSION_TYPES_H
#define EXPRESSION_TYPES_H

#include <stdint.h>

typedef enum {
    EMO_NORMAL = 0,
    EMO_HAPPY,
    EMO_FOCUS,
    EMO_ANGRY,
    EMO_SLEEP,
    EMO_SURPRISE,
    EMO_SAD,
    EMO_LOVE,
    EMO_COUNT
} Expression;

/* Assets declared in expression_assets.h (generated by make_assets.py) */

#endif
