#include "expression_engine.h"
#include "ili9341_fsmc.h"
#include "stm32f1xx_hal.h"

/*
 * Expression engine: manages expression display and animation.
 *
 * Images are stored in external C files (generated by png2rgb565.py).
 * Each expression can have 1-4 frames for animation.
 * Display area: 80×80 centered on 320×240 screen (x=120, y=80).
 */

/* The expression_table is defined in expression_assets.c */
/* Template that another AI / designer fills in */

/* Centered position for 80x80 expressions on 320x240 screen */
#define EXPR_X  ((ILI9341_WIDTH  - 80) / 2)  /* 120 */
#define EXPR_Y  ((ILI9341_HEIGHT - 80) / 2)  /* 80 */

static Expression  current_emo;
static uint8_t     current_frame;
static uint32_t    last_frame_tick;
static uint8_t     dirty;  /* force redraw on next tick */

void Expression_Init(void) {
    current_emo    = EMO_NORMAL;
    current_frame  = 0;
    last_frame_tick = 0;
    dirty           = 1;
}

void Expression_Set(Expression emo) {
    if (emo >= EMO_COUNT) return;
    if (emo == current_emo) return;

    current_emo   = emo;
    current_frame = 0;
    dirty         = 1;

    /* Clear background and redraw immediately */
    ILI9341_FillScreen(COLOR_BLACK);
}

Expression Expression_Get(void) {
    return current_emo;
}

void Expression_ForceRedraw(void) {
    dirty = 1;
}

void Expression_Tick(void) {
    const ExpressionDef *def = &expression_table[current_emo];
    uint32_t now = HAL_GetTick();

    /* Animation frame advance */
    if (def->frame_count > 1 && def->frame_interval_ms > 0) {
        if (now - last_frame_tick >= def->frame_interval_ms) {
            current_frame = (current_frame + 1) % def->frame_count;
            last_frame_tick = now;
            dirty = 1;
        }
    }

    /* Redraw if needed */
    if (dirty && def->frames[current_frame]) {
        uint16_t x = (ILI9341_WIDTH  - def->width)  / 2;
        uint16_t y = (ILI9341_HEIGHT - def->height) / 2;
        ILI9341_DrawBitmap(x, y, def->width, def->height,
                           def->frames[current_frame]);
        dirty = 0;
    }
}
