/*
 * Desktop Academic Assistant Robot - Main Application
 * STM32F103VET6 @ 72MHz, HAL Library, CubeMX generated base
 *
 * This file should be MERGED into the CubeMX-generated main.c.
 * Keep the CubeMX-generated initialization functions (MX_*_Init),
 * replace the while(1) loop and add the include blocks.
 */

/* ========== USER INCLUDES (add to CubeMX includes) ========== */
#include "ili9341_fsmc.h"
#include "rgb_led.h"
#include "uart_comm.h"
#include "touch_sensor.h"
#include "mpu6050_hal.h"
#include "rc522_spi.h"
#include "expression_engine.h"
#include "main_fsm.h"

/* ========== PRIVATE VARIABLES ========== */
/* CubeMX generates these as extern in main.h:
 *   I2C_HandleTypeDef hi2c1;
 *   SPI_HandleTypeDef hspi1;
 *   TIM_HandleTypeDef htim3;
 *   UART_HandleTypeDef huart1;
 */

/* ========== USER INITIALIZATION (after CubeMX MX_*_Init calls) ========== */
static void System_Init(void) {
    ILI9341_Init();
    RGB_Init();
    UART_Init();
    Touch_Init();
    MPU6050_Init();
    RC522_Init();
    FSM_Init();
}

/* ========== MAIN ========== */
int main(void) {
    /* CubeMX-generated init - DO NOT MODIFY */
    HAL_Init();
    SystemClock_Config();    /* generated by CubeMX */

    /* CubeMX peripheral init - generated */
    MX_GPIO_Init();
    MX_USART1_UART_Init();
    MX_I2C1_Init();
    MX_SPI1_Init();
    MX_TIM2_Init();
    MX_FSMC_Init();

    /* User application init */
    System_Init();

    UART_Printf("Desktop Assistant Ready\r\n");

    /* Main loop - non-blocking, all timing via HAL_GetTick() */
    while (1) {
        FSM_Tick();
        /* No HAL_Delay() - all timing handled by state machine */
    }
}

/* ========== EXTI CALLBACKS (add to stm32f1xx_it.c or keep here) ========== */

/*
 * Override HAL_GPIO_EXTI_Callback in main.c (weak function in HAL).
 * CubeMX generates stubs in stm32f1xx_it.c but the weak override works.
 */

void HAL_GPIO_EXTI_Callback(uint16_t GPIO_Pin) {
    if (GPIO_Pin == GPIO_PIN_4) {
        Touch_IRQ_Left();
    } else if (GPIO_Pin == GPIO_PIN_5) {
        Touch_IRQ_Right();
    }
}

/* ========== UART IDLE INTERRUPT (for DMA receive if used) ========== */
/*
 * If using DMA + IDLE for UART receive, add:
 *
 * void HAL_UARTEx_RxEventCallback(UART_HandleTypeDef *huart, uint16_t Size) {
 *     if (huart == &huart1) {
 *         for (uint16_t i = 0; i < Size; i++) {
 *             UART_ProcessByte(rx_dma_buf[i]);
 *         }
 *         HAL_UARTEx_ReceiveToIdle_DMA(&huart1, rx_dma_buf, DMA_BUF_SIZE);
 *     }
 * }
 */
